apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: config-controller
build:
  artifacts:
  - image: ghcr.io/semaforinformatik/config-controller
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: config-controller
        chartPath: helm
        version: 1.1.0
