apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-controller.fullname" . }}
  labels:
    {{- include "config-controller.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "config-controller.selectorLabels" . | nindent 4 }}
  ports:
    # Default port used by the image
    - name: http
      port: 3333
      targetPort: 3333

  # Service type (one of ClusterIP, NodePort, LoadBalancer, default is ClusterIP)
  type: ClusterIP
